### ISSUE TITLE
Breakdown of Screen properties is confusing

### ISSUE THREAD

**Issue by domenic** [spark008/screen-enumeration#10]
https://github.com/spark008/screen-enumeration/blob/master/EXPLAINER.md#proposal has three groups of properties:

```js
// Standardized properties in the Screen interface.

// Unstandardized properties in the Screen interface.

// NEW: Currently exposed as Window.devicePixelRatio.

// NEW: Properties currently not Web-exposed.
```

I'm having a hard time understanding what these each mean. Here is my best guess:

- Properties already existing in some spec
- Properties which are shipped in some (many? all?) browsers but do not exist in any spec
- A new property proposed by this proposal
- New properties proposed by this proposal

Are these guesses accurate? If so, does the scope of this proposal include standardizing the shipped-but-not-standardized properties? Could the comments be updated to be more explicit?

**Comment by michaelwasserman** [comment]
Thanks for the feedback! Your guesses are totally right, I'll attempt to clarify the breakdown and intention to standardize some shipped-but-not-standardized and entirely-new properties.

**Comment by michaelwasserman** [comment]
I refined the breakdown of screen properties within the explainer in a [recent change](https://github.com/spark008/screen-enumeration/commit/1171023326ce65e157474be3d1bb089dc070b63a), which should satisfy the main request of this issue. Please reopen this or file another issue if you have further feedback, thanks!
