### ISSUE TITLE
Screen.name will be hard to implement in a predictable way.

### ISSUE THREAD

**Issue by markafoltz** [spark008/screen-enumeration#13]
- Not all platforms provide access to this information. 
- An internal display may not have a name at all.
- The name has significant entropy for fingerprinting.
- It does not appear to be crucial for the use cases in the explainer.

When we shipped support for wired displays in Chrome via the Presentation API, we just ended up enumerating them as "Display 1", "Display 2" to get predictable behavior across platforms.

Do you see a compelling use case for exposing screen.name to the Web?

**Comment by michaelwasserman** [comment]
Thanks for this insight! "Display 1", "Display 2" matches our latest thinking, and the explainer mentions that, but I'll clarify.

**Comment by michaelwasserman** [comment]
The screen name has been replaced with an id.
