### ISSUE TITLE
touch support can already be feature detected

### ISSUE THREAD

**Issue by markafoltz** [spark008/screen-enumeration#14]
If the use case is determining whether to add touch event handlers to your application, there are existing [feature detection techniques](https://stackoverflow.com/questions/4817029/whats-the-best-way-to-detect-a-touch-screen-device-using-javascript/4819886#4819886) that can help.

If the use case is a web application that wants to know which screen to place a window that requires touch, screen.touchSupport could be useful?

**Comment by michaelwasserman** [comment]
Thanks for the link! Yes, both techniques have good use cases:
- Feature detection: optimize the content for touch-enabled (or not) displays where the window happens to be open.
- screen.touchSupport js introspection: Check the properties of multiple displays, place a window on the one with touch support (e.g. for conference rooms with big non-touch video screens and small touch-enabled controller screens)

I'll add this better use case to the explainer.

**Comment by michaelwasserman** [comment]
I believe the updated explainer addresses the desire to select screens by their properties, including touch support.
Please let me know if the proposal's language could better explicitly describe that goal.
