### ISSUE TITLE
Unsure how EDID relates to Screen.id

### ISSUE THREAD

**Issue by markafoltz** [spark008/screen-enumeration#15]
EDID is not just an ID, it's a [complete structure](https://en.wikipedia.org/wiki/Extended_Display_Identification_Data#Structure,_version_1.4) defined by VESA that includes a lot of metadata about the display, including manufacturer, serial number, colorimetry, power states, etc.

In fact, part of the point of the screen enumeration API (as far as I can tell) is to have the user agent parse this data and return a useful subset to the Web application.

Exposing the raw EDID to the Web is going to raise some issues as a display serial number is effectively a GUID for the user.

For the use cases you've proposed, would a simple counter suffice, i.e. primary display is given an ID of "Screen-0," then "Screen-1", "Screen-2", ...?

**Comment by michaelwasserman** [comment]
Thanks for this feedback! I've removed all mentions of EDID from the explainer, exposing that raw information is not in any current or future plans. Using a name or basic id, like "Screen 1" is in line with our current thinking.
