### ISSUE TITLE
Use cases for screen enumeration in service workers?

### ISSUE THREAD

**Issue by markafoltz** [spark008/screen-enumeration#16]
The explainer proposes exposing the screen enumeration API to service workers.

But I'm not sure what a service worker would do with this information; by design, they don't render content directly to the user.  The SW could trigger a notification that links to a page with content, but then it's that page that needs screen enumeration, not the SW.

Can you think of some use cases for screen enumeration in service workers?

**Comment by michaelwasserman** [comment]
Service workers could make use of this information when paired with proposed [Window Placement](https://github.com/spark008/window-placement) capabilities, if clients.openWindow is extended with optional parameters for target coordinates/screens. I'll add some more details in the explainer.

**Comment by michaelwasserman** [comment]
The current proposal doesn't expose any information to service workers; that notion has generally moved into the additional explorations document, which explores alternatives and potential extensions of the current proposal.
