### ISSUE TITLE
Interaction with virtual desktops?

### ISSUE THREAD

**Issue by markafoltz** [spark008/screen-enumeration#18]
Most modern OSes/window managers allow virtual desktops.

Is the UA encouraged or discouraged to use them as screens from the point of view of this API?

There seems to be an assumption that enumerated screens are all visible to the user.    In which case, virtual desktops should be specifically excluded from the API.

**Comment by michaelwasserman** [comment]
For now, we would discourage UAs from exposing other virtual desktops as Screens in this API; our intent is to only expose information about the one virtual desktop hosting the content. I'll aim to clarify this in the explainer(s).

**Comment by michaelwasserman** [comment]
I believe this is sufficiently covered by the [non-goal](https://github.com/webscreens/window-placement/blob/master/EXPLAINER.md#non-goals) of "Place windows outside a user's view or across virtual workspaces/desktops"
