### ISSUE TITLE
Screen change events?

### ISSUE THREAD

**Issue by inexorabletash** [spark008/screen-enumeration#2]
Screens can change:

* Displays can be added
* Displays can be removed
* Displays can be modified (e.g. moved, resized, color depth, etc) 

Should there be events for this, or is that out of scope/non-goal?

Potential inspiration: https://electronjs.org/docs/api/screen

**Comment by Garbee** [comment]
I'd like to know of some compelling use cases for the screen events before pushing one way or the other. I know what the software my company does currently with them, but that's mostly a work-around due to the complexity in our system.

I don't think I'd ever outright disagree with these being included. However for version 1 I would like a compelling use case before supporting it given the bandwidth to the problem scope.

**Comment by Garbee** [comment]
Looking through the Chromium Issue comments I saw a reference to https://signage.ninja/ . After peeking around one good use-case did come to me.

Let's say they've developed a menu that normally works across 5 screens. So it's out in production, but the restaurant has some problem. Let's just say, a power chord is pulled by accident. They can use the screen events to know exactly what happened, and re-structure the layout to fit all the content onto the available screen space as best they can. Without having to guess around as to what is happened and infer it from other sources.

With this type of use-case, I could see the events being beneficial to v1 to have.

**Comment by michaelwasserman** [comment]
I think there are a good number of use cases for events when displays are added/removed or when display properties change; I've included that in the "Future goals" section of the explainer. Polling for changes is not a great situation, so I'll consider bumping this up into "Current goals". Input from others here would be greatly appreciated. Thanks!

**Comment by nadavsinai** [comment]
Hi, getting the display configuration events would be useful for us too.
Currently, we only check if there were any changes in configuration upon application load, but having such events could help us deal with such changes in runtime.

**Comment by michaelwasserman** [comment]
I made screen change events part of the current explainer's proposal in a [recent change](https://github.com/spark008/screen-enumeration/commit/1171023326ce65e157474be3d1bb089dc070b63a), which should satisfy the main request of this issue. Please reopen this or file another issue if you have further feedback, thanks!
