### ISSUE TITLE
How are extended desktop arrangements represented?

### ISSUE THREAD

**Issue by markafoltz** [spark008/screen-enumeration#20]
Some OSes allow users to adjust the arrangement of the extended desktop across multiple monitors to suit their preferences, e.g. [Mac OS X](https://www.macobserver.com/tips/quick-tip/os-x-use-keyboard-shortcut-display-mirroring/).

The web application may want to know the alignment of one Screen object relative to another along their shared border. 

This may be handled by `screen.left` and `screen.top` already as the explainer suggests these reflect the *physical* arrangement of multiple displays.  But an explicit example might be helpful.

**Comment by michaelwasserman** [comment]
I haven't seen requests for this API itself to provide semantic layout descriptions, like shared borders. I think it's more generally valuable to provide basic information, like the relative location and bounds for each screen, reflecting the virtual arrangement of displays that comprise the extended desktop environment. That would be comparable to the information provided by the underlying OS or WM to native applications, and would allow developers to derive a semantic understanding of the display arrangement as needed. I'd be happy to hear requests or use cases for more semantic information from web developers. I'll add an example of the basic bounds information usage to the explainer.

**Comment by michaelwasserman** [comment]
Closing this issue, as positional information seems sufficient for the current proposal.
