### ISSUE TITLE
Async vs sync

### ISSUE THREAD

**Issue by beaufortfrancois** [spark008/screen-enumeration#24]
As raised by TAG review at https://github.com/w3ctag/design-reviews/issues/439#issuecomment-561902607, we may want to reconsider having an async API or not for enumerating screens.

**Comment by michaelwasserman** [comment]
Thanks for pointing that out! There are certainly trade-offs for each, here are some top of mind:
- Sync parallels `window.screen` and may be simpler for web devs (without permission gating?).
- Async allows non-blocking UA privacy interventions (e.g. permission checks/prompts).

Are there good patterns for permission gating with a synchronous access model?

**Comment by michaelwasserman** [comment]
It seems like most guidance has been toward an async API for screen information, mainly to support privacy protections.
The updated explainer [says something like](https://github.com/webscreens/window-placement/blob/master/EXPLAINER.md#add-getscreens-to-expose-information-about-available-screens) "By returning a promise, user agents can asynchronously determine what amount of information to expose, prompt users to decide, calculate the resulting values lazily, and reject or resolve accordingly."
The additional explorations doc considers synchronous access [here](https://github.com/webscreens/window-placement/blob/master/additional_explorations.md#alternative-synchronous-access-to-new-screen-information).
Feel free to reopen this issue or file a new issue if the topic should be explored further.
