### ISSUE TITLE
Potentially hold `layoutInfo` until a later spec revision

### ISSUE THREAD

**Issue by Garbee** [spark008/screen-enumeration#3]
> `Display.layoutInfo`: Info about the layout relative to other displays.

So, this currently based on the Chrome App API docs would be roughly how the screen is laid out in relation to the other screens. I think since this can be *inferred* from the other data provided, we should possibly consider holding off on shipping it in the specification.

My thought process here is that since it can be inferred, it may be better to do a library in JS of what we desire this data structure to look like and get more feedback on it in real-world usage without needing to go through it all with everything else in the v1 specification. This will allow some breathing room to get the core API right, allow libraries to abstract where they can, then consume those API structures internally later as the demand is proven and tested.

**Comment by michaelwasserman** [comment]
I totally agree, I'll remove it from the current proposal. Thanks!
