### ISSUE TITLE
Combine Screen Enumeration and Window Placement proposals?

### ISSUE THREAD

**Issue by michaelwasserman** [spark008/screen-enumeration#34]
Should we combine this Screen Enumeration proposal with [Window Placement](https://github.com/webscreens/window-placement)?

The two proposals are tightly coupled, and it might be easier to manage and digest a single repo that explores the full space of multi-screen information and cross-screen placement issues.

Perhaps in doing so, I could split out detailed aspects of each explainer into companion documents?

Input here is welcome.

**Comment by anssiko** [comment]
Makes sense given tight coupling and the fact there are no plans to implement just one but not the other AFAICT.

I challenge the group to come up with a concise yet descriptive name for the combined spec.

Let me know if you’d like to spin up a new repo under webscreens for the combined effort.

**Comment by michaelwasserman** [comment]
Thanks Anssi. I welcome repo name advice, and propose... \<drumroll/\>... "Window Placement"!
I'll start by moving Screen Enumeration issues and code into the Window Placement repo; wdyt?

**Comment by anssiko** [comment]
Please feel free to start consolidate content into the Window Placement repo. We can configure redirects when done. Sticking with the existing Window Placement name for the whole sounds like a plan as well 👍

**Comment by hober** [comment]
Hi, I got here via w3ctag/design-reviews#413.

Some TAG participants talked about this during a breakout today. While we each have our preferences re: one-big-spec v. many-small-specs, we think this is ultimately a question for the editors. You should do whatever best enables you to do your work.

**Comment by michaelwasserman** [comment]
Great! I merged the proposals into the [Window Placement](https://github.com/webscreens/window-placement) repo.
I'll transfer or close open issues here, then we can archive this repo.
