### ISSUE TITLE
Possible attribute for built in display being shut

### ISSUE THREAD

**Issue by Garbee** [spark008/screen-enumeration#5]
It is possible to configure built in laptop displays (or possibly something to do with new foldable devices with different technical screens) to be closed but still active.  This might be something we should expose through some property.

Use case: A presenter configures their layout on one set of monitors off the stage. Closes the lid, unplugs monitors and walks onto stage. Plugs projection things in, then opens lid.

The OS could initialize the built in display with the lid closed (thinking of MacOS possibly.) Then turn it off until the lid is opened. Or depending on the user configuration, leave it on and active even if closed.

There are many open questions in what OSes expose, how they expose it, and if it could be effectively utilized within an app to help manage state.

This kind of thing _should not_ be a blocker to the initial spec release, at least in my point of view. However, it is something to keep in mind with the complexities in this area for a later revision.

**Comment by michaelwasserman** [comment]
Great thought! I added a Display.hidden property to consider in the explainer:
https://github.com/spark008/screen-enumeration/commit/671d1d217025ad20691d4d11642745ebfb24cd68#diff-4298cc0cf8291ec04a133a6b0c0d459cR205
I'll aim to better describe uses cases like this soon and work on prioritization of properties for a possible V1; let's leave this issue open to make sure the use case gets captured somewhere.

**Comment by michaelwasserman** [comment]
I'm adding a super basic one-line use case for this and some other new potential Display properties. I'll dig into research and expanding specific details and use cases and as this proposal evolves. Let me know if you have more input or feedback as we forge ahead, thanks!
