### ISSUE TITLE
add information about monitor type (RGB/Monocrhome)

### ISSUE THREAD

**Issue by nadavsinai** [spark008/screen-enumeration#7]
Hi,
in our application, we need to know if to use colors in rendition. currently, we have no way to know but ask the user, if the API could provide that information it would be useful

Nadav Sinai
Web tech lead.
Alogtec-Philips

**Comment by Garbee** [comment]
We already have [monochrome in css](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/monochrome). Does your application care about a mix of displays or just the one being rendered upon?

**Comment by michaelwasserman** [comment]
I was about to suggest checking [Screen.colorDepth or pixelDepth](https://www.w3.org/TR/cssom-view-1/#screen), but then I saw:
"Note: The colorDepth and pixelDepth attributes are useless but are included for compatibility."
That's frustrating; I'll make a note in the explainer about that.

**Comment by michaelwasserman** [comment]
I added a note that should capture the deficiency, need, and possible solutions here:
https://github.com/spark008/screen-enumeration/commit/afc7e25e7a9120f5c226bb30a94d50b7b29cfa5c#diff-4298cc0cf8291ec04a133a6b0c0d459c
Please reopen the issue if this needs additional attention.

**Comment by michaelwasserman** [comment]
And thanks!
